### ISSUE TITLE
Cannot set properties of undefined (setting 'value')

### ISSUE THREAD

**Issue by tommie** [manuelmeister/remark-attributes#4]
Thanks for publishing this package!

It looks like mdast-util-from-markdown has changed their API so `exit` no longer returns the top node: https://github.com/syntax-tree/mdast-util-from-markdown/commit/18f4bb0f1b720fd30f1c3a7b11e1fac90aa6903f

It's released as 2.0.0.

Replacing

```ts
const node = this.exit(token);
```

with 

```ts
const node =  this.stack[this.stack.length - 1];
this.exit(token);
```

seems to do the trick. I couldn't find any helper function to get the top of the stack.

**Comment by tommie** [comment]
I'll interpret the emoji as "yes it's a bug, and patches are accepted" :)

**Comment by manuelmeister** [comment]
Yes, sorry. I'll look into it this week.

**Comment by manuelmeister** [comment]
Thanks for the work! ❤️ 

I tried it out and it first seemed that it broke link attributes inside lists, but I figured, that it was already broken before 🤪
